FROM nginx:alpine

RUN adduser -D -H -u 1000 -s /bin/bash www-data && rm /etc/nginx/conf.d/default.conf
WORKDIR /usr/app/src/dist

COPY ./docker/nginx.conf /etc/nginx/
COPY ./docker/sites/*.conf /etc/nginx/sites-available/
COPY ./ /usr/app/src
CMD ["nginx"]

EXPOSE 8083
