version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: docker-compose -f docker/docker-compose.yml build --no-cache oms-frontend
  lint:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install Node
          command: |
            curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
            sudo apt-get install -y nodejs
            echo 'export PATH=/usr/bin:$PATH' >> $BASH_ENV
            which node && node -v
      - run: npm install
      - run: npm run lint
  audit:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: npm audit
  docker-build-and-push:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: docker build  --tag aegee/oms-frontend:$(node -p "require('./package.json').version") --tag aegee/oms-frontend:latest -f ./docker/Dockerfile .
      - run: docker login --username $DOCKER_LOGIN --password $DOCKER_PASSWORD
      - run: docker push aegee/oms-frontend:$(node -p "require('./package.json').version")
      - run: docker push aegee/oms-frontend:latest


workflows:
  version: 2
  build:
    jobs:
      - build
  lint:
    jobs:
      - lint
  audit:
    jobs:
      - audit
  docker-build-and-push:
    jobs:
      - docker-build-and-push:
          filters:
            branches:
              only: master
