version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: docker-compose -f docker/docker-compose.yml build --no-cache oms-frontend
      - run: docker-compose -f docker/docker-compose.yml up oms-frontend
  lint:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install Node
          # shell: /bin/sh --login pipefail
          command: |
            curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
            sudo apt-get install -y nodejs
            echo 'export PATH=/usr/bin:$PATH' >> $BASH_ENV
            echo $PATH
            which node && node -v
      - run: echo $PATH
      - run: npm install
      - run: npm run lint
  audit:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: npm audit


workflows:
  version: 2
  build:
    jobs:
      - build
  lint:
    jobs:
      - lint
  audit:
    jobs:
      - audit
