version: "2.4"

services:
    oms-frontend:
        restart: always
        image: aegee/oms-frontend:stable
        #healthcheck?
        cpu_count: 1
        mem_limit: 900m
        labels:
            - "traefik.frontend.rule=Host:${SUBDOMAIN_FRONTEND}${BASE_URL};PathPrefix:/"
            - "traefik.frontend.priority=11"
            - "traefik.port=80"
            - "traefik.backend=oms-frontend"
            - "traefik.enable=true"

networks:
    default:
        external:
            name: OMS
