version: "3.4"

services:
    oms-frontend:
        restart: always
        image: aegee/oms-frontend:latest
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 3
        # cpu_count: 1
        # mem_limit: 900m
        labels:
            - "traefik.frontend.rule=Host:${SUBDOMAIN_FRONTEND}${BASE_URL};PathPrefix:/"
            - "traefik.frontend.priority=11"
            - "traefik.port=80"
            - "traefik.backend=oms-frontend"
            - "traefik.enable=true"

networks:
    default:
        external:
            name: OMS
