version: '3.2'

services:
    oms-frontend:
        restart: always
        build:
            context: ./$PATH_OMS_FRONTEND/..
            dockerfile: ./docker/Dockerfile
        image: aegee/oms-frontend:dev
        volumes:
            - "./$PATH_OMS_FRONTEND/../:/usr/app/src"
        labels:
            - "traefik.frontend.rule=Host:${SUBDOMAIN_FRONTEND}${BASE_URL};PathPrefix:/"
            - "traefik.frontend.priority=11"
            - "traefik.port=80"
            - "traefik.backend=oms-frontend"
            - "traefik.enable=true"

networks:
  default:
    external:
      name: OMS
