version: "3.4"

services:
    oms-frontend:
        build:
            context: ./${PATH_OMS_FRONTEND}/..
            dockerfile: ./docker/Dockerfile
        image: aegee/oms-frontend:dev
        volumes:
            - /usr/app/src/node_modules
