version: "3.4"

services:
    frontend:
        build:
            context: ./${PATH_FRONTEND}/..
            dockerfile: ./docker/Dockerfile
        image: aegee/frontend:dev
        volumes:
            - ./${PATH_FRONTEND}/../:/usr/app/src
            - /usr/app/src/node_modules
