version: '3.2'

services:
    oms-frontend-builder:
        restart: on-failure
        build:
            context: ./$PATH_OMS_FRONTEND/oms-frontend/
            dockerfile: ./Dockerfile.dev
        image: aegee/oms-frontend-builder
        volumes:
            - "./$PATH_OMS_FRONTEND/../:/usr/app/src"

    oms-frontend-nginx:
        restart: always
        build:
            context: ./$PATH_OMS_FRONTEND/oms-frontend-nginx/
            dockerfile: ./Dockerfile.dev
        image: aegee/oms-frontend
        volumes:
            - "./$PATH_OMS_FRONTEND/../:/usr/app/src"
        # expose:
        #     - 80
        labels:
            - "traefik.frontend.rule=Host:${SUBDOMAIN_FRONTEND}${BASE_URL};PathPrefix:/"
            - "traefik.frontend.priority=11"
            - "traefik.port=80"
            - "traefik.backend=oms-frontend-nginx"
            - "traefik.enable=true"

networks:
  default:
    external:
      name: OMS
