version: '3.2'

services:
    oms-frontend:
        restart: always
        build:
            context: ./$PATH_OMS_FRONTEND/..
            dockerfile: ./docker/Dockerfile
        volumes:
            - "./$PATH_OMS_FRONTEND/../:/usr/app/src"
