version: "3.4"

services:
    oms-frontend:
        build:
            context: ./${PATH_OMS_FRONTEND}/..
            dockerfile: ./docker/Dockerfile
        image: aegee/oms-frontend:dev
        volumes:
            - /usr/app/src/node_modules
            - ./${PATH_OMS_FRONTEND}/../:/usr/app/src
        command: "/bin/sh /usr/app/scripts/bootstrap-dev.sh" #FIXME: npm is not present in the final img
