version: "3.4"

services:
    oms-frontend:
        build:
            context: ./${PATH_OMS_FRONTEND}/..
            dockerfile: ./docker/Dockerfile
        image: aegee/oms-frontend:latest
        volumes:
            - /usr/app/src/node_modules
            - ./${PATH_OMS_FRONTEND}/../:/usr/app/src
        command: npm install && npm run build && chmod 777 /usr/app/src && nginx
