version: '3.2'

services:
    oms-frontend:
        build:
            context: ./$PATH_OMS_FRONTEND/..
        restart: no #this is just the build container
    oms-frontend-nginx:
        build:
            context: ./$PATH_OMS_FRONTEND/..
            dockerfile: Dockerfile.nginx
        restart: always
        labels:
            - "traefik.frontend.rule=HostRegexp:{domain:[a-z0-9.]+};PathPrefix:/"
            - "traefik.frontend.priority=11"
            - "traefik.port=80"
            - "traefik.backend=oms-frontend"
            - "traefik.enable=true"
            - "registry.status=status.json"
            - "registry.modules=getModules.json"

networks:
  default:
    external:
      name: OMS
